// Copia de MUNICIPIOS_POR_DEPARTAMENTO (ver frontend/src/listas.js) para poder validar en el
// backend que el municipio recibido realmente pertenece al departamento recibido. Si algún día
// se actualiza la lista en el frontend, hay que actualizar esta también para que no se desajusten.

export const MUNICIPIOS_POR_DEPARTAMENTO = {
  "Atlántida": ["Arizona", "El Porvenir", "Esparta", "Jutiapa", "La Ceiba", "La Masica", "San Francisco", "Tela"],
  "Choluteca": ["Apacilagua", "Choluteca", "Concepción de María", "Duyure", "El Corpus", "El Triunfo", "Marcovia", "Morolica", "Namasigue", "Orocuina", "Pespire", "San Antonio de Flores", "San Isidro", "San José", "San Marcos de Colon", "Santa Ana de Yusguare"],
  "Colón": ["Balfate", "Bonito Oriental", "Iriona", "Limón", "Sabá", "Santa Fe", "Santa Rosa de Aguán", "Sonaguera", "Tocoa", "Trujillo"],
  "Comayagua": ["Ajuterique", "Comayagua", "El Rosario", "Esquias", "Humuya", "La Libertad", "La Trinidad", "Lamani", "Las Lajas", "Lejamaní", "Meambar", "Minas de Oro", "Ojos de Agua", "San Jerónimo", "San José de Comayagua", "San José del Potrero", "San Luis", "San Sebastian", "Siguatepeque", "Taulabe", "Villa de San Antonio"],
  "Copán": ["Cabañas", "Concepción", "Copán Ruinas", "Corquín", "Cucuyagua", "Dolores", "Dulce Nombre", "El Paraíso", "Florida", "La Jigua", "La Union", "Nueva Arcadia", "San Agustín", "San Antonio", "San Jeronimo", "San José", "San Juan de Opoa", "San Nicolas", "San Pedro", "Santa Rita", "Santa Rosa de Copán", "Trinidad de Copán", "Veracruz"],
  "Cortés": ["Choloma", "La Lima", "Omoa", "Pimienta", "Potrerillos", "Puerto Cortés", "San Antonio de Cortés", "San Francisco de Yojoa", "San Manuel", "San Pedro Sula", "Santa Cruz de Yojoa", "Villanueva"],
  "El Paraíso": ["Alauca", "Danli", "El Paraíso", "Guinope", "Jacaleapa", "Liure", "Moroceli", "Oropoli", "Potrerillos", "San Antonio de Flores", "San Lucas", "San Matias", "Soledad", "Teupasenti", "Texiguat", "Trojes", "Vado Ancho", "Yauyupe", "Yuscaran"],
  "Francisco Morazán": ["Alubaren", "Cedros", "Curaren", "Distrito Central", "El Porvenir", "Guaimaca", "La Libertad", "La Venta", "Lepaterique", "Maraita", "Marale", "Nueva Armenia", "Ojojona", "Orica", "Reitoca", "Sabanagrande", "San Antonio de Oriente", "San Buenaventura", "San Ignacio", "San Juan de Flores", "San Miguelito", "Santa Ana", "Santa Lucia", "Talanga", "Tatumbla", "Valle de Ángeles", "Vallecillo", "Villa de San Francisco"],
  "Gracias a Dios": ["Ahuas", "Brus Laguna", "Juan Francisco Bulnes", "Puerto Lempira", "Ramón Villeda Morales", "Wampusirpi"],
  "Intibucá": ["Camasca", "Colomoncagua", "Concepción", "Dolores", "Intibuca", "Jesús de Otoro", "La Esperanza", "Magdalena", "Masaguara", "San Antonio", "San Francisco de Opalaca", "San Isidro", "San Juan", "San Marcos de Sierra", "San Miguelito", "Santa Lucia", "Yamaranguila"],
  "Islas de la Bahía": ["Guanaja", "José Santos Guardiola", "Roatan", "Utila"],
  "La Paz": ["Aguanqueterique", "Cabanas", "Cane", "Chinacla", "Guajiquiro", "La Paz", "Lauterique", "Marcala", "Mercedes de Oriente", "Opatoro", "San Antonio del Norte", "San José", "San Juan", "San Pedro de Tutule", "Santa Ana", "Santa Elena", "Santa María", "Santiago de Puringla", "Yarula"],
  "Lempira": ["Belen", "Candelaria", "Cololaca", "Erandique", "Gracias", "Gualcince", "Guarita", "La Campa", "La Iguala", "La Union", "La Virtud", "Las Flores", "Lepaera", "Mapulaca", "Piraera", "San Andres", "San Francisco", "San Juan Guarita", "San Manuel Colohete", "San Marcos de Caiquin", "San Rafael", "San Sebastian", "Santa Cruz", "Talgua", "Tambla", "Tomala", "Valladolid", "Virginia"],
  "Ocotepeque": ["Belen Gualcho", "Concepción", "Dolores Merendon", "Fraternidad", "La Encarnacion", "La Labor", "Lucerna", "Mercedes", "Ocotepeque", "San Fernando", "San Francisco del Valle", "San Jorge", "San Marcos", "Santa Fe", "Sensenti", "Sinuapa"],
  "Olancho": ["Campamento", "Catacamas", "Concordia", "Dulce Nombre de Culmi", "El Rosario", "Esquipulas del Norte", "Gualaco", "Guarizama", "Guata", "Guayape", "Jano", "Juticalpa", "La Union", "Mangulile", "Manto", "Patuca", "Salama", "San Esteban", "San Francisco de Becerra", "San Francisco de la Paz", "Santa María del Real", "Silca", "Yocon"],
  "Santa Bárbara": ["Arada", "Atima", "Azacualpa", "Ceguaca", "Chinda", "Concepción del Norte", "Concepción del Sur", "El Nispero", "Gualala", "Ilama", "Las Vegas", "Macuelizo", "Naranjito", "Nueva Celilac", "Nueva Frontera", "Petoa", "Protección", "Quimistan", "San Francisco de Ojuera", "San José de Colinas", "San Luis", "San Marcos", "San Nicolas", "San Pedro Zacapa", "San Vicente Centenario", "Santa Barbara", "Santa Rita", "Trinidad"],
  "Valle": ["Alianza", "Amapala", "Aramecina", "Caridad", "Goascoran", "Langue", "Nacaome", "San Francisco de Coray", "San Lorenzo"],
  "Yoro": ["Arenal", "El Negrito", "El Progreso", "Jocon", "Morazan", "Olanchito", "Santa Rita", "Sulaco", "Victoria", "Yorito", "Yoro"]
};
