export const DEPARTAMENTOS_HONDURAS = [
  "Atlántida",
  "Choluteca",
  "Colón",
  "Comayagua",
  "Copán",
  "Cortés",
  "El Paraíso",
  "Francisco Morazán",
  "Gracias a Dios",
  "Intibucá",
  "Islas de la Bahía",
  "La Paz",
  "Lempira",
  "Ocotepeque",
  "Olancho",
  "Santa Bárbara",
  "Valle",
  "Yoro"
];

export const MUNICIPIOS_POR_DEPARTAMENTO = {
  "Atlántida": ["Arizona", "El Porvenir", "Esparta", "Jutiapa", "La Ceiba", "La Masica", "San Francisco", "Tela"],
  "Choluteca": ["Apacilagua", "Choluteca", "Concepción de María", "Duyure", "El Corpus", "El Triunfo", "Marcovia", "Morolica", "Namasigue", "Orocuina", "Pespire", "San Antonio de Flores", "San Isidro", "San José", "San Marcos de Colon", "Santa Ana de Yusguare"],
  "Colón": ["Balfate", "Bonito Oriental", "Iriona", "Limón", "Sabá", "Santa Fe", "Santa Rosa de Aguán", "Sonaguera", "Tocoa", "Trujillo"],
  "Comayagua": ["Ajuterique", "Comayagua", "El Rosario", "Esquias", "Humuya", "La Libertad", "La Trinidad", "Lamani", "Las Lajas", "Lejamaní", "Meambar", "Minas de Oro", "Ojos de Agua", "San Jerónimo", "San José de Comayagua", "San José del Potrero", "San Luis", "San Sebastian", "Siguatepeque", "Taulabe", "Villa de San Antonio"],
  "Copán": ["Cabañas", "Concepción", "Copán Ruinas", "Corquín", "Cucuyagua", "Dolores", "Dulce Nombre", "El Paraíso", "Florida", "La Jigua", "La Union", "Nueva Arcadia", "San Agustín", "San Antonio", "San Jeronimo", "San José", "San Juan de Opoa", "San Nicolas", "San Pedro", "Santa Rita", "Santa Rosa de Copán", "Trinidad de Copán", "Veracruz"],
  "Cortés": ["Choloma", "La Lima", "Omoa", "Pimienta", "Potrerillos", "Puerto Cortés", "San Antonio de Cortés", "San Francisco de Yojoa", "San Manuel", "San Pedro Sula", "Santa Cruz de Yojoa", "Villanueva"],
  "El Paraíso": ["Alauca", "Danli", "El Paraíso", "Guinope", "Jacaleapa", "Liure", "Moroceli", "Oropoli", "Potrerillos", "San Antonio de Flores", "San Lucas", "San Matias", "Soledad", "Teupasenti", "Texiguat", "Trojes", "Vado Ancho", "Yauyupe", "Yuscaran"],
  "Francisco Morazán": ["Alubaren", "Cedros", "Curaren", "Distrito Central", "El Porvenir", "Guaimaca", "La Libertad", "La Venta", "Lepaterique", "Maraita", "Marale", "Nueva Armenia", "Ojojona", "Orica", "Reitoca", "Sabanagrande", "San Antonio de Oriente", "San Buenaventura", "San Ignacio", "San Juan de Flores", "San Miguelito", "Santa Ana", "Santa Lucia", "Talanga", "Tatumbla", "Valle de Ángeles", "Vallecillo", "Villa de San Francisco"],
  "Gracias a Dios": ["Ahuas", "Brus Laguna", "Juan Francisco Bulnes", "Puerto Lempira", "Ramón Villeda Morales", "Wampusirpi"],
  "Intibucá": ["Camasca", "Colomoncagua", "Concepción", "Dolores", "Intibuca", "Jesús de Otoro", "La Esperanza", "Magdalena", "Masaguara", "San Antonio", "San Francisco de Opalaca", "San Isidro", "San Juan", "San Marcos de Sierra", "San Miguelito", "Santa Lucia", "Yamaranguila"],
  "Islas de la Bahía": ["Guanaja", "José Santos Guardiola", "Roatan", "Utila"],
  "La Paz": ["Aguanqueterique", "Cabanas", "Cane", "Chinacla", "Guajiquiro", "La Paz", "Lauterique", "Marcala", "Mercedes de Oriente", "Opatoro", "San Antonio del Norte", "San José", "San Juan", "San Pedro de Tutule", "Santa Ana", "Santa Elena", "Santa María", "Santiago de Puringla", "Yarula"],
  "Lempira": ["Belen", "Candelaria", "Cololaca", "Erandique", "Gracias", "Gualcince", "Guarita", "La Campa", "La Iguala", "La Union", "La Virtud", "Las Flores", "Lepaera", "Mapulaca", "Piraera", "San Andres", "San Francisco", "San Juan Guarita", "San Manuel Colohete", "San Marcos de Caiquin", "San Rafael", "San Sebastian", "Santa Cruz", "Talgua", "Tambla", "Tomala", "Valladolid", "Virginia"],
  "Ocotepeque": ["Belen Gualcho", "Concepción", "Dolores Merendon", "Fraternidad", "La Encarnacion", "La Labor", "Lucerna", "Mercedes", "Ocotepeque", "San Fernando", "San Francisco del Valle", "San Jorge", "San Marcos", "Santa Fe", "Sensenti", "Sinuapa"],
  "Olancho": ["Campamento", "Catacamas", "Concordia", "Dulce Nombre de Culmi", "El Rosario", "Esquipulas del Norte", "Gualaco", "Guarizama", "Guata", "Guayape", "Jano", "Juticalpa", "La Union", "Mangulile", "Manto", "Patuca", "Salama", "San Esteban", "San Francisco de Becerra", "San Francisco de la Paz", "Santa María del Real", "Silca", "Yocon"],
  "Santa Bárbara": ["Arada", "Atima", "Azacualpa", "Ceguaca", "Chinda", "Concepción del Norte", "Concepción del Sur", "El Nispero", "Gualala", "Ilama", "Las Vegas", "Macuelizo", "Naranjito", "Nueva Celilac", "Nueva Frontera", "Petoa", "Protección", "Quimistan", "San Francisco de Ojuera", "San José de Colinas", "San Luis", "San Marcos", "San Nicolas", "San Pedro Zacapa", "San Vicente Centenario", "Santa Barbara", "Santa Rita", "Trinidad"],
  "Valle": ["Alianza", "Amapala", "Aramecina", "Caridad", "Goascoran", "Langue", "Nacaome", "San Francisco de Coray", "San Lorenzo"],
  "Yoro": ["Arenal", "El Negrito", "El Progreso", "Jocon", "Morazan", "Olanchito", "Santa Rita", "Sulaco", "Victoria", "Yorito", "Yoro"]
};

export const ZONAS_FIHNEC = [
  "Aguán 1",
  "Aguán 2",
  "Aguán 3",
  "Atlántica 1",
  "Atlántica 2",
  "Atlántica Insular",
  "Central 1a",
  "Central 1b",
  "Central 2",
  "Central 3",
  "Central 4",
  "Centro Occidente 1",
  "Centro Occidente 2a",
  "Centro Occidente 2b",
  "Centro Occidente 3",
  "Centro Occidente 4",
  "Nor Occidente",
  "Norte 1",
  "Norte 2",
  "Norte 3",
  "Norte 4",
  "Occidente 1",
  "Occidente 2",
  "Occidente 3",
  "Occidente 4a",
  "Occidente 4b",
  "Occidente 5",
  "Oriental 1a",
  "Oriental 1b",
  "Oriental 1c",
  "Oriental 2",
  "Sur a"
];

export const CARGOS_FIHNEC = [
  "Presidente de JDN",
  "Vice Presidente JDN",
  "Secretario JDN",
  "Tesorero JDN",
  "Fiscal JDN",
  "Presidente de Capítulo",
  "Vice Presidente de Capítulo",
  "Secretario de Capítulo",
  "Tesorero de Capítulo",
  "Servidor de Capítulo",
  "Director Zonal",
  "Sub Director Zonal",
  "Director Regional",
  "Representante de Campo",
  "Director Nacional de Eventos Estratégicos",
  "Sub Director Nacional de Eventos Estratégicos",
  "Coordinador Zonal de Eventos Estratégicos",
  "Coordinador Regionales de Eventos Estratégicos",
  "Director Nacional de Membresía",
  "Sub Director Nacional de Membresía",
  "Coordinador Zonal de Membresía",
  "Director Nacional de Oración e Intercesión",
  "Sub Director Nacional de Oración e Intercesión",
  "Coordinador Zonal de Oración e Intercesión",
  "Director Nacional de DINACAP",
  "Sub Director Nacional de DINACAP",
  "Director Nacional SEMAT",
  "Sub Director Nacional SEMAT",
  "Director DINACAP",
  "Sub Director DINACAP",
  "Coordinador Zonal de DINACAP",
  "Director Nacional de SAEL",
  "Sub Director Nacional de SAEL",
  "Servidor de SAEL",
  "Director Nacional de Capítulos y Grupos Empresariales e Institucionales",
  "Sub Director Nacional de Grupos FIHNEC e Instituciones Militares y Policiales",
  "Coordinador Zonal de Grupos FIHNEC e Instituciones Militares y Policiales",
  "Director Nacional de la Voz y Literatura",
  "Sub Director Nacional de la Voz y Literatura",
  "Coordinador Zonal de la Voz y Literatura",
  "Director Nacional de Apoyo / Expansión Territorial",
  "Director Nacional Adjunto de Apoyo / Expansión Territorial",
  "Director Nacional de Comunicaciones e Internet",
  "Director Nacional DRAS",
  "Sub Director Nacional DRAS",
  "Coordinador Zonal DRAS",
  "Servidor",
  "Servidor del SFL"
];

export const ESTADOS_CIVILES = ["Soltero", "Casado", "Viudo", "Divorciado"];

export const TIPOS_TESTIMONIO = ["No comparte", "Personal", "Familiar", "Matrimonio", "Internacional", "Otro"];

export const FORMACION_OFICIAL = [
  "Escuela de la Visión", "LGMFT", "SAEL", "SFL I", "SFL II", "SFL III", "SFL IV", "SEMAT", "SEPREL"
];

export const OTRAS_PARTICIPACIONES = [
  "Encuentros Zonales", "Encuentros Nacionales", "Convenciones Nacionales", "Convención Internacional",
  "Vigilias de Capítulo", "Vigilias de Equipo", "Vigilias Zonales"
];
